### PR TITLE
Allow usage of latest node-wordpress 1.3.x release

### PR DESCRIPTION
**Pull request by staabm**

### CODE REVIEW

**Comment by scottgonzalez** [comment]
This change is fine, but since you're changing one, can you change all of them?

**Comment by scottgonzalez** [comment]
Looks like the other dependencies should be updated to much newer versions, so I'll leave it to you whether you keep the current versions and just switch the tilde ranges to caret ranges or if you also update the versions to the latest major versions and verify nothing has broken.

**Comment by staabm** [comment]
Updated the others as well. Usually one want to define the lowest possible version so keeping those and just changing the operator makes it compatible with most versions and libs (spans the biggest net of version)

**Comment by scottgonzalez** [comment]
> Usually one want to define the lowest possible version so keeping those and just changing the operator makes it compatible with most versions and libs

Except for anything current ;-) Caret ranges don't allow major version updates and the current versions listed are not the current majors (sans wordpress).

**Pull request closed without merging**
